### PR TITLE
Fixed typographical error, changed accross to across in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@Railk, I've corrected a typographical error in the documentation of the [T3S](https://github.com/Railk/T3S) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by Railk** [comment]
@orthographic-pedant i didn't know the meaning of linguistic squalor (but thanks to your pseudonyme i could guess the meaning ;p) i had to translate it, in french it's even more strong "misère linguistique" rien que ça ! Ca ma fait rire merci :) and i accept your pull request. May the orthographic force be with you !

**Comment by thoppe** [comment]
I am at a loss for words -- "misère linguistique" is beautiful. Too bad @orthographic-pedant doesn't correct french.

**Comment by Railk** [comment]
@thoppe yes too bad that would be a nice addition to your orthographic bot.

**Comment by orthographic-pedant** [comment]
Indeed. If you ever would like to create the French version you've already
got the name! All you have to do is fork this repository and starting
correcting the world!

**Pull request merged**
